---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    template: {{.Release.Name}}
    app: image-clone-controller
  name: image-clone-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-clone-controller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: image-clone-controller
    spec:
      containers:
      - name: controller
        imagePullPolicy: IfNotPresent
        image: {{.Values.controller.image}}:{{.Values.controller.imagetag}}
        envFrom:
        - secretRef:
            name: {{.Values.backupRegistry.secret}}
        args:
        - "--backup-registry={{.Values.backupRegistry.name}}"
        - "--registry-org={{.Values.backupRegistry.organization}}"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: {{.Values.serviceaccount}}
