---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Name}}
  labels:
    template: {{.Release.Name}}
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Name}}
  labels:
    template: {{.Release.Name}}
subjects:
- kind: ServiceAccount
  name: {{.Values.serviceaccount}}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{.Release.Name}}
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm-admin
  namespace: {{.Release.Namespace}}
  labels:
    template: {{.Release.Name}}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm-admin
  namespace: {{.Release.Namespace}}
  labels:
    template: {{.Release.Name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cm-admin
subjects:
- kind: ServiceAccount
  name: {{.Values.serviceaccount}}
  namespace: {{.Release.Namespace}}
