---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.backupRegistry.secret}}
  labels:
    template: {{.Release.Name}}
data:
  IMG_CTR_REGISTRY_USERNAME: {{.Values.backupRegistry.username | b64enc | quote}}
  IMG_CTR_REGISTRY_PASSWORD: {{.Values.backupRegistry.password | b64enc | quote}}
